# Generated by Django 4.1.4 on 2022-12-28 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(choices=[('Pyro', 'Pyro'), ('Cryo', 'Cryo'), ('Hydro', 'Hydro'), ('Geo', 'Geo'), ('Anemo', 'Anemo'), ('Electro', 'Electro'), ('Dendro', 'Dendro')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resonance', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GIRng.character')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GIRng.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='GIRng.TeamInfo', to='GIRng.character'),
        ),
        migrations.AddField(
            model_name='character',
            name='element',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GIRng.element'),
        ),
    ]
