# Generated by Django 4.1.4 on 2022-12-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIRng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='element',
            field=models.CharField(choices=[('Pyro', 'Pyro'), ('Cryo', 'Cryo'), ('Hydro', 'Hydro'), ('Geo', 'Geo'), ('Anemo', 'Anemo'), ('Electro', 'Electro'), ('Dendro', 'Dendro')], max_length=7),
        ),
        migrations.DeleteModel(
            name='Element',
        ),
    ]
